### ISSUE TITLE
Alerta de condição no turno do Personagem

### ISSUE THREAD

**Issue by Asascar** [coppolaop/DungeonManager#106]
**Descreva aqui a sua sugestão**
Adicionar um alerta que comunique as condições ativas no turno do personagem.

**Em que parte do sistema esta funcionalidade entraria**
No combate

**Como você gostaria**
Quando chegar a vez de um personagem o alerta seria exibido, caso ele possuísse uma ou mais condições. Esse alerta informaria não só a condição como também os acréscimos e/ou decréscimos feitos de maneira automática.

**Utilidade**
Evitar que os jogadores e/ou mestre deixem o efeito passar desapercebido.

**Comment by coppolaop** [comment]
@Asascar , atualmente existe uma funcionalidade que possibilita marcar o personagem com condições.
A ideia inicial era pra usar como contagem automática para efeitos de sangramento, incremento temporário em CA ou cura por turno...
Acredito que ele possa atender ao que você precisa.
Dê uma olhada na Issue #79 e na issue #103 .
Se não atender, podemos pensar em alguma implementação que atenda.
Fique à vontade nos comentário, vamos trocando ideia.

**Comment by Asascar** [comment]
@coppolaop a principio eu também achei que a funcionalidade citada já englobava o caso citado, mas ao fazer testes com a mesma vi que não é o caso.

Ao aplicar um efeito de incremento de CA com duração 10 turnos e valor 2 por exemplo, todo turno ele aumenta 2 de ca do alvo, sendo que a intenção é o alvo receber +2 de CA durante 10 turnos, além do fato das condições da forma que estão implementadas só influenciam a CA e o HP e tem condições que podem influenciar até a iniciativa do alvo.

E antes que eu esqueça, parabéns pelo programa.
Eu tinha um projeto de fazer algo parecido em python mas ao analisar seu projeito preferi utilizar o mesmo e estou disponível para ajudar no que puder.

**Comment by coppolaop** [comment]
Obrigado, @Asascar.
Fique à vontade para contribuir. Ainda estou preparando a documentação sobre GIT(explicando como funcionariam os pull requests e o padrão de commit), sobre as nomeclaturas de variável e outros pequenos detalhes que sigo à risca. Mas se quiser ir ajudando, tenta seguir o molde que eu já uso, qualquer coisa eu informo como comentário no pull request.

Sobre o exemplo que você citou, edita a condição e põe ela como "não continua".
Eu mesmo achei esse termo "contínuo" algo ruim e abri a issue #105 para trocar o nome.
Um efeito continuo seria um efeito que acontece todo turno, como sangramento.
Já um efeito "não contínuo" seria um efeito que realiza uma alteração no inicio e reverte a alteração no seu fim, como incremento temporário de CA.
A issue #103 também foi algo que notei no ultimo teste, há efeitos como "velocidade" que afetam atributos que não são mapeados pela aplicação, então há a necessidade do campo "outros".
Essas duas alterações que citei ainda não estão disponíveis em uma release, mas serão entregue em breve na versão 1.4.1 .
Se você tiver interesse em utilizar uma versão que já possua essas alterações, pode baixar o branch develop do projeto e compilá-lo. Se não conseguir, comenta aqui que eu gero uma pré-release pra você, ainda não tenho data pra próxima versão.

Veja se essas correções que eu citei atendem ao que você espera.
Qualquer coisa, só comentar.

**Comment by Asascar** [comment]
Vou compilar aqui e te dou um feedback.

dei uma olhada nas issues citadas (#103 e #105) e concordo com as mudanças citadas.
gostei particularmente a sugestão do alerta para os jogadores e seria interessante esse alerta (pode ser em forma de caixa de dialogo ou até mesmo no log) informar todas condições afetando aquele personagem e o fim de qualquer condição que venha acontecer.

Eu não tenho muita experiencia com o Github, então vou dar uma estudada aqui e conforme eu for aprendendo a usar vou sugerindo edições.

**Comment by coppolaop** [comment]
No log, a mensagem chega a ser impressa, mas acho que a mensagem seguinte acaba sobrescrevendo. No arquivo de log da pasta deve dar pra ver, mas acho melhor essa sua ideia do Alerta, pois ele chama mais atenção e não corre risco do Mestre deixar passar desapercebido.
Assim que você tiver visto como ficaram as outras alterações, a gente aproveita essa própria issue pra documentar essa sugestão do alerta e o que tiver faltando. Vou editar o texto quando fecharmos uma ideia.

**Comment by Asascar** [comment]
@coppolaop ao tentar compilar aqui está dando erro, não sei se é pela minha limitação de conhecimento na linguagem ou pela falta de alguma biblioteca na minha máquina virtual.

Se puder gerar um pré-release para testes, seria ótimo.

**Comment by coppolaop** [comment]
Vou gerar hoje a noite e comento aqui.
Pra você conseguir gerar na sua máquina, vai precisar do Java JDK 8.
Eu recomendaria compilar pelo Eclipse IDE.

**Comment by coppolaop** [comment]
@Asascar ,
Segue a Pré-release:
https://github.com/coppolaop/DungeonManager/releases/tag/1.4.1-beta .
Depois me passa um feedback se as ultimas correções estão atendendo.
Nessa versão tem a correção #103 e #105 .

**Comment by Asascar** [comment]
@coppolaop as correções #103 e #105 estão ótimas, a adição de atributo "outro" e a alteração do "efeito contínuo" são de grande ajuda.
parabéns.

Hoje tem sessão e as alterações vão fazer a diferença na hora do combate.

**Comment by coppolaop** [comment]
Perfeito, @Asascar .
Vou alterar o texto desse chamado para incluir a sua sugestão de alerta ao chegar a vez de um personagem com determinada condição.
Em breve lanço a release nova, assim que esse chamado for fechado, você já pode baixar.
Se durante a partida encontrar mais alguma sugestão, só abrir um chamado!
Grande abraço e Boas Rolagens!

**Comment by coppolaop** [comment]
Reabri a Issue pois vou utilizar ela para tratar desse alerta. Alterei seu texto inicial e o nome do chamado, @Asascar .

**Comment by coppolaop** [comment]
@Asascar, finalizamos hoje a release que engloba essas alterações a tanto tempo prometidas.
Fique à vontade para baixar. Sendo essa a release mais atual, a mensagem de download não vai ficar aparecendo na tela da forma como o compilado de pré-release exibe ao iniciar.
Segue o Link:
https://github.com/coppolaop/DungeonManager/releases/tag/1.5.0
