### ISSUE TITLE
Adicionar jogador encerra o combate

### ISSUE THREAD

**Issue by Asascar** [coppolaop/DungeonManager#107]
**Descreva o Bug**
Durante um combate, caso você tenha de adicionar um personagem que ainda não esteja "cadastrado" no sistema você não consegue retornar para o combate em andamento.

**Para reproduzir**
O passo-a-passo feito para encontrá-lo:
1. Vá em 'Arquivo'
2. Clique em 'listar personagens (já que o mesmo ainda não se encontra na lista, não é possível adicionar o mesmo pelo botão de adicionar'.
3. Ao tentar retornar para o combate não há uma opção para isso.

**Por favor, complete as seguintes informações:**
 - Seu Sistema Operacional: Windows 10
 - Java 13.0.1
 - A versão que você está utilizando do Dungeon Manager: 1.4.0

**Informações adicionais**
O bug é facilmente contornável ao abrir outra instancia do programa e adicionar o personagem por lá, fazendo com que ele apareça na lista de personagens a ser adicionados, porém acredito que esse método ser contra intuitivo e que poderia haver uma maneira mais fácil de realizar o procedimento.

**Comment by coppolaop** [comment]
Desculpa a demora na resposta @Asascar, não tinha visto essa issue.
O mesmo vale pra efeitos novos, você não consegue criá-los durante o combate.
Eu recomendo abrir uma nova janela do Dungeon Manager, criar por ela e depois adicionar na anterior, não consigo pensar em uma forma boa para "pausar o combate".

**Comment by Asascar** [comment]
@coppolaop desculpa a demora, a solução que achei foi justamente a que sugeriu e sigo usando a mesma, por isso vou fechar esta issue
