### ISSUE TITLE
Iniciativa de Personagens adicionados após o combate iniciar

### ISSUE THREAD

**Issue by Asascar** [coppolaop/DungeonManager#108]
**Descreva aqui a sua sugestão**
Rolar a iniciativa do personagem adicionado após o início do combate.

**Como funciona hoje**
Ao adicionar alguém ao combate depois dele ter começado o mesmo é adicionado como último da rodada, sem direito a testes.

**Como você gostaria**
Ao adicionar alguém ao combate o mesmo tenha direito ao teste de iniciativa para se verificar onde ele vai entrar na ordem de iniciativa.

**Comment by coppolaop** [comment]
Estou um pouco parado com esse projeto pq estou estudando uma tecnologia pra melhorar a interface dele. Inclui essa Issue na próxima entrega, vou tentar priorizar pra fechar logo essa versão.

**Comment by Asascar** [comment]
Eu não sou mt de Java e nem mt experiente, mas no que eu puder ajudar, só falar.

Eu estava pensando em criar uma Issue para integrar a parte de inimigos com um banco de dados, mas vou tentar desenvolver isso aqui e te mandar já feito. (tenho uma base SQLite já com os monstros)

**Comment by coppolaop** [comment]
Eu estou estudando **Electron**, é a mesma tecnologia usada pelo Whatsapp desktop, pelo Discord, pelo visual studio code e até pelo próprio Github desktop. Usa basicamente Javascript, HTML e CSS.

Sobre a questão q vc levantou sobre banco, acho que o caminho mais viável seria você fazer uma aplicação q pegue esses dados da base e gere os arquivos JSON pro Dungeon Manager. Seria um aplicativo apartado.
Dá pra integrar o Dungeon Manager a um banco de dados, mas acho isso muito custoso, pois seria necessária a instalação de um banco na maquina do usuário, ou caso o banco fique remoto, seria necessária uma hospedagem(e conexão do usuário com a internet).
