### ISSUE TITLE
Adicionar PDM iguais sem a necessidade de novos arquivos.

### ISSUE THREAD

**Issue by Flaigor** [coppolaop/DungeonManager#46]
**Descreva aqui a sua sugestão**
Usar o mesmo arquivo de PDM para vários indivíduos, sendo que, eles precisão ter as mesmas características inicias, porém dentro da batalha, as modificações devem ser individuais.

**Em que parte do sistema esta funcionalidade entraria**
Na hora de incluir personagens (Tela principal).

**Como você gostaria**
Exemplo: 
Arquivo: Soldado_Generico_nv5.properties;
mostrado do programa : Soldado_Generico_nv5
Caso seja adicionado mais de um Soldado_Generico_nv5.
dentro de batalha haverá:
Soldado_Generico_nv5_00
Soldado_Generico_nv5_01
Soldado_Generico_nv5_02 
...
Soldado_Generico_nv5_99

**Utilidade**
Evita o trabalho de criar vários arquivos iguais, assim minimizando os  erros.

**Comment by coppolaop** [comment]
Codificado
