### ISSUE TITLE
Exibir imagem ao selecionar personagem

### ISSUE THREAD

**Issue by coppolaop** [coppolaop/DungeonManager#55]
**Descreva aqui a sua sugestão**
Ao selecionar o personagem durante o combate, o sistema poderia exibir uma imagem cadastrada na ficha.

**Em que parte do sistema esta funcionalidade entraria**
- Tabela de combate

**Como você gostaria**
Ao clicar na linha referente ao personagem na tabela de combate, a imagem do personagem apareceria no canto direito.

**Utilidade**
Apenas para identificação de cada personagem. Também para a estética da aplicação.

**Comment by coppolaop** [comment]
Esta issue será exclusiva para exibição da imagem.
Foi criada a issue #75 para a parte de cadastro da imagem.

**Comment by vitor-abel** [comment]
Teste realizado.
Alteração aprovada.
[Evidencia01.87.pdf](https://github.com/coppolaop/DungeonManager/files/3304281/Evidencia01.87.pdf)

**Comment by vitor-abel** [comment]
Teste realizado.
Alteração aprovada.
[Evidencia01.55.pdf](https://github.com/coppolaop/DungeonManager/files/3308487/Evidencia01.55.pdf)
