### ISSUE TITLE
Descrição de personagem na sua criação 

### ISSUE THREAD

**Issue by Flaigor** [coppolaop/DungeonManager#65]
**Descreva aqui a sua sugestão**
Funcionalidade que permite dar uma descrição mais detalhada do personagem (tanto PDM quanto PJ) na sua criação.

**Em que parte do sistema esta funcionalidade entraria**
Na tela de criação de personagem, deve haver uma caixa onde o mestre pode adicionar descrições sobre o personagem.

**Como você gostaria**
Essa descrição deve ser capaz de suportar vários caracteres (Incluindo caracteres especiais), ter a possibilidade de pular linha e caso a descrição esteja maior que a caixa, uma barra de rolagem vertical será implementada.

**Utilidade**
Essa função permitirá que o mestre adicione informações especificas de cada personagem (Para diferentes sistemas), além de comentarias para lhe ajudar no combate.

**Comment by coppolaop** [comment]
Iniciando testes.

**Comment by coppolaop** [comment]
Teste realizado.
Alteração aprovada.
[Evidencia.01.65.pdf](https://github.com/coppolaop/DungeonManager/files/3293546/Evidencia.01.65.pdf)
