### ISSUE TITLE
Relatório de alteração usando personagem errado

### ISSUE THREAD

**Issue by Flaigor** [coppolaop/DungeonManager#70]
**Descreva o Bug**
Na tela de batalha, quando há um personagem e uma réplica dele mesmo, o log se confunde caso um cause dano ou cure o outro.
Caso haja na mesma batalha um personagem original (Bárbaro_Nv5 ) e uma réplica (Bárbaro_Nv5 (1)), quando é a vez do Bárbaro_Nv5 (1) e é feita a alteração no Bárbaro_Nv5, o relatório retorna como se o Bárbaro_Nv5  tivesse feito a ação com ele mesmo, o mesmo acontece caso o Bárbaro_Nv5 (1) tenha seu valor alterado no turno do Bárbaro_Nv5.

**Para reproduzir**
O passo-a-passo feito para encontrá-lo:
1. Inicie uma batalha.
2. Adicione uma réplica e um original do mesmo personagem.
3. Faça uma alteração do Hp Atual do original estando no turno da réplica.
4. Veja o erro.

**Comportamento esperado**
O relatório deve retornar que a réplica curou ou causou dano no original ou que o original curou ou causou dano na réplica. Atualmente o retorno do log é "Algo fez com que o personagem perdesse x de hp " ou "O personagem se curou x de hp ".

**Por favor, complete as seguintes informações:**
 - Seu Sistema Operacional: Windows 10
 - A versão que você está utilizando do Dungeon Manager: 1.2.1

**Comment by coppolaop** [comment]
O erro só acontece caso o valor de HP Atual seja alterado utilizando operadores (+ ou -).
No caso de valores fixos o programa funciona como esperado.

**Comment by coppolaop** [comment]
Este bug foi ocasionado pela falta de alteração de uma parte do arquivo PersonagemCombateTableModel.java durante a correção da issue #46 .
