### ISSUE TITLE
Opção de adicionar mais de uma réplica por vez

### ISSUE THREAD

**Issue by Flaigor** [coppolaop/DungeonManager#74]
**Descreva aqui a sua sugestão**
Dentro da tela de combate, quando for adicionar replicas, deve existir uma opção onde se pode informar a quantidade de réplicas do mesmo personagem.
Essa função ira ajudar os mestres a adicionarem muitos personagem de uma unica vez, poupando tempo e paciência. 

**Como funciona hoje**
O programa só permite adicionar uma réplica por vez, isso torna o trabalho do mestre em adicionar novos elementos no combate um pouco trabalhoso.

**Como você gostaria**
A ideia é ter dentro da caixa "Adicionar personagem no combate" uma combobox com o número de réplicas que vão ser adicionadas no momento.

**Informações Adicionais**
O número dentro da combobox por default deve ser 1 e deve conter números inteiros positivos não nulo.

**Comment by coppolaop** [comment]
Caso seja realmente utilizada uma combobox para inserir o valor, minha sugestão é que haja um scroll dentro da parte das opções para que o tamanho não extrapole o tamanho do monitor.

**Comment by coppolaop** [comment]
Teste realizado.
Alteração aprovada.
[Evidencia01.74.pdf](https://github.com/coppolaop/DungeonManager/files/3294578/Evidencia01.74.pdf)
