### ISSUE TITLE
Lista de personagens selecionados expandindo demais

### ISSUE THREAD

**Issue by coppolaop** [coppolaop/DungeonManager#76]
**Descreva o Bug**
Ao incluir muitos personagens no combate, a lista de personagens da tela inicial acaba crescendo para baixo de maneira a ficar impossível de se ler quais personagens foram escolhidos à partir do 30°.

**Para reproduzir**
O passo-a-passo feito para encontrá-lo:
1. Adicione mais de 30 personagens na tela inicial
2. Veja o erro

**Comportamento esperado**
Que exista um scroll que permita visualizar toda a lista dentro da tela.

**Por favor, complete as seguintes informações:**
 - Seu Sistema Operacional: Windows 10
 - A versão que você está utilizando do Dungeon Manager: 1.2.2

**Comment by vitor-abel** [comment]
Teste realizado.
Alteração aprovada.
[Evidencia01.76.pdf](https://github.com/coppolaop/DungeonManager/files/3293625/Evidencia01.76.pdf)
