### ISSUE TITLE
JSpinner não aceita dados do usuário

### ISSUE THREAD

**Issue by Flaigor** [coppolaop/DungeonManager#78]
**Descreva o Bug**
O JSpinner dentro de adicionar personagem no combate, não recebe dados do usuário.

**Para reproduzir**
O passo-a-passo feito para encontrá-lo:
1. Inicie um combate.
2. Clique em "Adicionar personagem".
3. Digite um número dentro do JSpinner.
4. Veja o erro.

**Comportamento esperado**
O JSpinner deve aceitar dados do usuário e adicionar a quantidade de réplicas correspondente ao número digitado.

**Por favor, complete as seguintes informações:**
 - Seu Sistema Operacional: Windows 10
 - A versão que você está utilizando do Dungeon Manager: 1.3.0 (Beta)

**Comment by vitor-abel** [comment]
Teste realizado.
Alteração aprovada.
[Evidencia01.78.pdf](https://github.com/coppolaop/DungeonManager/files/3360329/Evidencia01.78.pdf)
