### ISSUE TITLE
Finalização no log após fechamento da aplicação

### ISSUE THREAD

**Issue by coppolaop** [coppolaop/DungeonManager#81]
**Descreva aqui a sua sugestão**
O aplicativo deve exibir a mensagem de finalização do combate no log caso a aplicação seja fechada durante um combate ou caso o usuário troque de tela, finalizando indiretamente o combate.

**Como funciona hoje**
Caso a aplicação seja fechada, o log continua em aberto, sem finalização.
A mensagem de finalização só é gerada caso todos os personagens sejam removidos do combate.

**Como você gostaria**
Quando o usuário sair da tela de combate, sendo através da escolha de uma nova tela ou fechando a aplicação, a mensagem de finalização deve ser exibida no log, assim como quando acontece caso todos os personagens sejam removidos do combate.

**Comment by vitor-abel** [comment]
Teste realizado.
A mensagem não apareceu, o que indica que o bug não foi resolvido.
[Evidencia01.81.pdf](https://github.com/coppolaop/DungeonManager/files/3360502/Evidencia01.81.pdf)

**Comment by coppolaop** [comment]
Resolvido e testado junto à issue #92
