### ISSUE TITLE
Finalizar combate não retorna para tela principal 

### ISSUE THREAD

**Issue by Flaigor** [coppolaop/DungeonManager#83]
**Descreva o Bug**
Iniciando um combate, após remover todos os integrantes, o programa não retorna a tela principal.

**Para reproduzir**
O passo-a-passo feito para encontrá-lo:
1. Inicie um combate.
2. Clique em Remover personagem 
3. Remova todos os personagens.
4. Veja o erro

**Comportamento esperado**
Após a remoção de todos os personagens, o programa deveria voltar automaticamente para a tela principal.

**Por favor, complete as seguintes informações:**
 - Seu Sistema Operacional: Windows 10
 - A versão que você está utilizando do Dungeon Manager: 1.3.0

**Informações adicionais**
O programa retorna para a tela inicial caso o usuário clique em "Remover personagem" com a tabela vazia.

**Comment by coppolaop** [comment]
Iniciando testes

**Comment by coppolaop** [comment]
Teste realizado.
Alteração aprovada.
[Evidencia01.83.pdf](https://github.com/coppolaop/DungeonManager/files/3418579/Evidencia01.83.pdf)
