### ISSUE TITLE
Descrição de personagem durante combate

### ISSUE THREAD

**Issue by coppolaop** [coppolaop/DungeonManager#86]
**Descreva aqui a sua sugestão**
Na tela de combate, disponibilizar a descrição do personagem ( #65 ) ao selecioná-lo.

**Em que parte do sistema esta funcionalidade entraria**
Na tela de combate.

**Como você gostaria**
Que houvesse a exibição da descrição durante o combate e que esta descrição fosse editável.

**Utilidade**
Permitir o verdadeiro uso da descrição criada na issue #65.

**Informações Adicionais**
Este campo será extremamente útil para os usuários preencherem com informações específicas do sistema de RPG que usam ou com regras específicas da mesa.

**Comment by coppolaop** [comment]
Para realizar a correção, a função que realizava a atualização do arquivo properties foi transferida da classe _PersonagemCombateTableModel.java_ para a classe _PersonagemController.java_. Esta transferência se deu por dois motivos: Funcionalidades desse tipo devem ficar em classes do tipo Controller e a funcionalidade precisava ser acessível em outra parte do projeto.

**Comment by vitor-abel** [comment]
Teste realizado.
Alteração aprovada, embora ainda haja um problema quanto as réplicas (#89 )
[Evidencia01.86.pdf](https://github.com/coppolaop/DungeonManager/files/3293723/Evidencia01.86.pdf)
