### ISSUE TITLE
Erro na inclusão de réplicas da tela inicial

### ISSUE THREAD

**Issue by coppolaop** [coppolaop/DungeonManager#87]
**Descreva o Bug**
Ao retirar e re-adicionar uma réplica, o sistema duplica a réplica já gerada.

**Para reproduzir**
O passo-a-passo feito para encontrá-lo:
1. Na tela inicial, Adicione três réplicas do mesmo PDM
2. Remova a réplica número 2
3. Adicione outra réplica deste PDM
4. Veja o erro

**Comportamento esperado**
O sistema não deve, em hipótese alguma, ter dois números de réplica iguais para o mesmo personagem.

**Por favor, complete as seguintes informações:**
 - Seu Sistema Operacional: Windows 8.1
 - A versão que você está utilizando do Dungeon Manager: 1.2.2

**Comment by vitor-abel** [comment]
Teste realizado.
Alteração aprovada.
[Evidencia01.87.pdf](https://github.com/coppolaop/DungeonManager/files/3293611/Evidencia01.87.pdf)
