### ISSUE TITLE
Valores muito altos na criação / edição de personagem travando o programa

### ISSUE THREAD

**Issue by vitor-abel** [coppolaop/DungeonManager#91]
Na criação ou edição de personagem, ao tentar colocar valores muito altos (acima de 2147483647) nos campos HP, CA ou Bônus de Iniciativa o programa trava. Além disso, sempre que iniciado novamente fica uma tela branca e o programa só volta a funcionar normalmente caso o personagem seja deletado nos arquivos.

**Para reproduzir**
O passo-a-passo feito para encontrá-lo:
1. Vá em Arquivo e selecione Listar Personagens
2. Clique em Novo PJ ou Editar PJ
3. Tente colocar valores maiores que 2147483647
4. Veja o erro

**Comportamento esperado**
Deveria exibir uma mensagem informando que o valor é inválido

**Por favor, complete as seguintes informações:**
 - Seu Sistema Operacional: Windows 8.1
 - A versão que você está utilizando do Dungeon Manager: 1.2.2

**Comment by coppolaop** [comment]
Além deste problema, o sistema também não está apto para receber valores negativos. Sendo assim, a correção de ambos os problemas será entregue junto a este chamado.

**Comment by coppolaop** [comment]
Iniciando testes

**Comment by coppolaop** [comment]
Teste realizado.
Alteração aprovada.
[Evidencia01.91.pdf](https://github.com/coppolaop/DungeonManager/files/3415646/Evidencia01.91.pdf)
