### ISSUE TITLE
Mensagem de log ao fechar aplicação

### ISSUE THREAD

**Issue by vitor-abel** [coppolaop/DungeonManager#92]
**Descreva o Bug**
Após a resolução da issue #81, está ocorrendo um bug ao fechar a aplicação, já que a mensagem de fim de combate continua não aparecendo no caso de um fechamento abrupto do sistema.

**Para reproduzir**
O passo-a-passo feito para encontrá-lo:
1. Inicie um combate
2. Feche abruptamente o sistema (clicando no X no lado superior direito da janela)
3. Veja o erro no log

**Comportamento esperado**
O sistema deveria indicar no log quando um combate é encerrado mesmo se o programa for encerrado durante o combate.

**Por favor, complete as seguintes informações:**

 - Seu Sistema Operacional: Windows 8.1
 - A versão que você está utilizando do Dungeon Manager: 1.3.0 (beta)

**Comment by coppolaop** [comment]
Iniciando testes

**Comment by coppolaop** [comment]
Teste realizado.
Alteração aprovada.
[Evidencia01.92.pdf](https://github.com/coppolaop/DungeonManager/files/3415616/Evidencia01.92.pdf)
